DITest/Controllers/SaleOrderController.cs
using AutoMapper;
using DITest.DTO.Models;
using DITest.Models;
using DITest.Service.Services.Interfaces;
using DITtest.Service.Services.Interfaces;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DITest.Controllers
{
    public class SaleOrderController : Controller
    {
        private readonly ISalesOrderService service;
        private readonly ISalesOrderItemService salesOrderItemService;

        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(SaleOrderController));  //Declaring Log4Net

        public SaleOrderController(ISalesOrderService service, ISalesOrderItemService salesOrderItemService)
        {
            this.service = service;
            this.salesOrderItemService = salesOrderItemService;
        }

        // GET: SaleOrder
        public ActionResult Index()
        {
            logger.Error("boo");
            return View(Mapper.Map<IEnumerable<SaleOrderDTO>, IEnumerable<SalesOrder>>(service.GetAllSaleOrder()));
        }

        // GET: SaleOrder
        public ActionResult IndexDiv()
        {
            logger.Error("boo");
            return View(Mapper.Map<IEnumerable<SaleOrderDTO>, IEnumerable<SalesOrder>>(service.GetAllSaleOrder()));
        }

        public ActionResult Edit(int saleOrderId)
        {
            return View(Mapper.Map<SaleOrderDTO, SalesOrder>(service.GetSaleOrderById(saleOrderId)));
        }

        public ActionResult Create()
        {
            return View(new SalesOrder());
        }

        [HttpPost]
        public ActionResult Create(SalesOrder salesOrder)
        {
            service.Save(Mapper.Map<SalesOrder, SaleOrderDTO>(salesOrder));
            return RedirectToAction("Index");
        }

        public ActionResult CreateDialog()
        {
            return base.PartialView("_CreateDialog", new SalesOrder());
        }

        [HttpPost]
        public ActionResult CreateDialog(SalesOrder salesOrder)
        {
            service.Save(Mapper.Map<SalesOrder, SaleOrderDTO>(salesOrder));
            return RedirectToAction("Index");
        }

        public ActionResult EditAddress(int saleOrderId)
        {
            return base.PartialView("_EditAddress", Mapper.Map<SaleOrderDTO, SalesOrder>(service.GetSaleOrderById(saleOrderId)));
        }

        [HttpPost]
        public ActionResult EditAddress(SalesOrder salesOrder)
        {
            service.Save(Mapper.Map<SalesOrder, SaleOrderDTO>(salesOrder));
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int saleOrderId)
        {
            service.Delete(saleOrderId);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveSaleOrder(int saleOrderId, string fullName)
        {
            return PartialView("_RemoveSaleOrder", new SalesOrder() { SaleOrderId = saleOrderId, FullName = fullName });
        }

        [HttpPost]
        public ActionResult RemoveSaleOrder(SalesOrder salesOrder)
        {
            service.Delete(salesOrder.SaleOrderId);
            return RedirectToAction("Index");
        }

        public ActionResult AddSaleOrderItem(int saleOrderId)
        {
            return base.PartialView("_AddSaleOrderItem", new SalesOrderItem() { SaleOrderId = saleOrderId });
        }

        [HttpPost]
        public ActionResult AddSaleOrderItem(SalesOrderItem SalesOrderItem)
        {
            salesOrderItemService.Save(Mapper.Map<SalesOrderItem, SaleOrderItemDTO>(SalesOrderItem));
            return RedirectToAction("Index");
        }

        public ActionResult ShowItemList(int saleOrderId)
        {
            var list = Mapper.Map<IEnumerable<SaleOrderItemDTO>, IEnumerable<SalesOrderItem>>(salesOrderItemService.GetBySaleOrderId(saleOrderId));
            return PartialView("_SaleOrderItems", list);
        }

        public ActionResult SaveData(SalesOrderItem d)
        {
            if (ModelState.IsValid)
            {
                salesOrderItemService.Save(Mapper.Map<SalesOrderItem, SaleOrderItemDTO>(d));
                return Json(new { success = true });
            }
            else
            {
                return base.PartialView("_AddSaleOrderItem", d);
                // return Json(new { success = false });
            }
        }
    }
}

DITest/Controllers/SaleOrderItemController.cs
using DITest.Models;
using System.Web.Mvc;

namespace DITest.Controllers
{
    public class SaleOrderItemController : Controller
    {
        // GET: SaleOrderItem
        public ActionResult Add(int saleOrderId)
        {
            return View("AddSaleOrderItem", new SalesOrderItem() { SaleOrderId = saleOrderId });
        }

        [HttpPost]
        public ActionResult Add(SalesOrderItem model)
        {
            return View("AddSaleOrderItem", model);
        }
    }
}

DITest/Views/SaleOrder/Create.cshtml
@model DITest.Models.SalesOrder

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SalesOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SaleOrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleOrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleOrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineOne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineOne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineOne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineTwo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineTwo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineTwo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DITest/Views/SaleOrder/Edit.cshtml
@model DITest.Models.SalesOrder

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SalesOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SaleOrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleOrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleOrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineOne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineOne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineOne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineTwo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineTwo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineTwo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        @DateTime.Now.ToString("yyyy-MM-ddTHH:mmzzz")

        <div id="itemsList">

            @Ajax.ActionLink("Update outer",
                            "ShowItemList",
                            new { saleOrderId = Model.SaleOrderId },
                            new AjaxOptions
                            {
                                UpdateTargetId = "itemsList",
                                InsertionMode = InsertionMode.Replace,
                                HttpMethod = "GET",
                            },
                            new { @class = "btn btn-primary" })

            @Html.Partial("_SaleOrderItems", Model.SaleOrderItem)
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/App/SaleOrder/Edit.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")

@*@Scripts.Render("~/bundles/jquery")*@

}

DITest/Views/SaleOrder/Index.cshtml
@model IEnumerable<DITest.Models.SalesOrder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<button type="button" class="btn btn-primary" id="btnCreateDialog" data-toggle="modal" data-target="#dialogEdit">
    Create Dialog
</button>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SaleOrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressLineOne)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressLineTwo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullAddress)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SaleOrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressLineOne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressLineTwo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullAddress)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { saleOrderId = item.SaleOrderId }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { saleOrderId = item.SaleOrderId })

                <button type="button" class="btn btn-primary" id="btnEdit" data-saleOrderId=@item.SaleOrderId data-toggle="modal" data-target="#dialogEdit">
                    Edit
                </button>

                <button type="button" class="btn btn-primary" id="btnRemoveSaleOrder" data-saleOrderId=@item.SaleOrderId data-fullName=@item.FullName data-toggle="modal" data-target="#dialogEdit">
                    Remove Sale Order
                </button>
            </td>
        </tr>
    }
</table>

@section Scripts {
    <script src="~/Scripts/App/SaleOrder/Edit.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

DITest/Views/SaleOrder/IndexDiv.cshtml
@model IEnumerable<DITest.Models.SalesOrder>

@{
    ViewBag.Title = "IndexDiv";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>IndexDiv</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="divTable">
    <div class="divTableBody">
        <div class="divTableRow">
            <div class="divTableCell">@Html.DisplayNameFor(model => model.SaleOrderId)</div>
            <div class="divTableCell">@Html.DisplayNameFor(model => model.FullName)</div>
            <div class="divTableCell">@Html.DisplayNameFor(model => model.AddressLineOne)</div>
            <div class="divTableCell">@Html.DisplayNameFor(model => model.AddressLineTwo)</div>
            <div class="divTableCell">@Html.DisplayNameFor(model => model.FullAddress)</div>
            <div class="divTableCell"> </div>
        </div>

        @foreach (var item in Model)
        {
            <div class="divTableRow divTableRowBackgroundColour">
                <div class="divTableCell">@Html.DisplayFor(model => item.SaleOrderId)</div>
                <div class="divTableCell">@Html.DisplayFor(model => item.FullName)</div>
                <div class="divTableCell">@Html.DisplayFor(model => item.AddressLineOne)</div>
                <div class="divTableCell">@Html.DisplayFor(model => item.AddressLineTwo)</div>
                <div class="divTableCell">@Html.DisplayFor(model => item.FullAddress)</div>
                <div class="divTableCell"> </div>
            </div>
                <div class="divTableRow divTableRowBackgroundColour">
                    <div class="divTableCell"> </div>
                    <div class="divTableCell"> </div>
                    <div class="divTableCell"> </div>
                    <div class="divTableCell"> </div>
                    <div class="divTableCell"> </div>
                    <div class="divTableCell"> </div>
                </div>
        }
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/App/Shared/divTable.js"></script>
    <link href="~/Content/divTable.css" rel="stylesheet" />
}

DITest/Views/SaleOrder/_AddSaleOrderItem.cshtml
@model DITest.Models.SalesOrderItem

@*@using (Ajax.BeginForm("SaveData", "SaleOrder",null,
    new AjaxOptions() { HttpMethod = "post", OnSuccess = "ajaxSuccess" }
    ,null
))*@

@using (Ajax.BeginForm("SaveData", new AjaxOptions() { HttpMethod = "post", OnSuccess = "ajaxSuccess" }
            ))

{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SalesOrderItem</h4>
        <hr />

        @Ajax.ActionLink("Update Dialog",
                            "ShowItemList",
                            new { saleOrderId = 1 },
                            new AjaxOptions
                            {
                                UpdateTargetId = "itemsList",
                                InsertionMode = InsertionMode.Replace,
                                HttpMethod = "GET",
                            },
                            new { @class = "btn btn-primary" })

        <button type="button" class="btn btn-primary" id="btnShowItemList" data-saleOrderId=1 data-toggle="modal" data-target="#dialogEdit">
            btnShowItemList
        </button>

    <button type="submit" class="btn btn-primary" value="Create"
            id="btnSubmitConsultation">
        Save
    </button>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SaleOrderItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleOrderItemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleOrderItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaleOrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleOrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleOrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>*@

        <p>
            <input type="submit" value="Create" />
        </p>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DITest/Views/SaleOrder/_CreateDialog.cshtml
@model DITest.Models.SalesOrder

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Sales Order</h4>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SaleOrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleOrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleOrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineOne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineOne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineOne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineTwo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineTwo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineTwo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" value="Create"> Save </button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DITest/Views/SaleOrder/_EditAddress.cshtml
@model DITest.Models.SalesOrder

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">@Model.FullName</h4>
        </div>

        @Html.HiddenFor(model => model.FullName)

        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineOne, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineOne, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineOne, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLineTwo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLineTwo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLineTwo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" id="btnSave"> Save </button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DITest/Views/SaleOrder/_RemoveSaleOrder.cshtml
@model DITest.Models.SalesOrder

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Delete </h4>
</div>

@Html.HiddenFor(model => model.SaleOrderId)

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="form-group">
            <div class="control-label col-md-12">
                Are You sure you want to delete item @Model.FullName
            </div>
        </div>

        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" value="Delete"> Delete </button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
    </div>
}

DITest/Views/SaleOrder/_SaleOrderItems.cshtml
@model IEnumerable<DITest.Models.SalesOrderItem>

@DateTime.Now.ToString("yyyy-MM-ddTHH:mmzzz")
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@Ajax.ActionLink("Update Inner",
                            "ShowItemList",
                            new { saleOrderId = 1},
                            new AjaxOptions
                            {
                                UpdateTargetId = "itemsList",
                                InsertionMode = InsertionMode.Replace,
                                HttpMethod = "GET",
                            },
                            new { @class = "btn btn-primary" })

<button type="button" class="btn btn-primary" id="btnAdd" data-saleOrderId=1 data-toggle="modal" data-target="#dialogEdit">
    Add
</button>

@Html.ActionLink("Create New",  "Add", "SaleOrderItem", new { SaleOrderId = 1 }, null)

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SaleOrderItemId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SaleOrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SaleOrderItemId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SaleOrderId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            <button type="button" class="btn btn-primary" id="btnEdit" data-saleOrderId=@item.SaleOrderId data-toggle="modal" data-target="#dialogEdit">
                Edit
            </button>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}
</table>